language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  - name: staging-started
    if: tag is present
  - name: staging
    if: tag is present
  - name: staging-finished
    if: tag is present

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - stage: production
      name: GAM Service
      script: npx @base-cms/website-deployment-tool deploy-service gam gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: GAM Service
      script: npx @base-cms/website-deployment-tool deploy-service gam gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - stage: production
      name: American Machinist
      script: npx @base-cms/website-deployment-tool deploy americanmachinist.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: American Machinist
      script: npx @base-cms/website-deployment-tool deploy americanmachinist.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: American School & University
      script: npx @base-cms/website-deployment-tool deploy asumag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: American School & University
      script: npx @base-cms/website-deployment-tool deploy asumag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Bulk Transporter
      script: npx @base-cms/website-deployment-tool deploy bulktransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Bulk Transporter
      script: npx @base-cms/website-deployment-tool deploy bulktransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Contracting Business
      script: npx @base-cms/website-deployment-tool deploy contractingbusiness.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Contracting Business
      script: npx @base-cms/website-deployment-tool deploy contractingbusiness.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Contractor
      script: npx @base-cms/website-deployment-tool deploy contractormag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Contractor
      script: npx @base-cms/website-deployment-tool deploy contractormag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: EC&M
      script: npx @base-cms/website-deployment-tool deploy ecmweb.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: EC&M
      script: npx @base-cms/website-deployment-tool deploy ecmweb.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: EHS Today
      script: npx @base-cms/website-deployment-tool deploy ehstoday.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: EHS Today
      script: npx @base-cms/website-deployment-tool deploy ehstoday.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Electrical Marketing
      script: npx @base-cms/website-deployment-tool deploy electricalmarketing.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Electrical Marketing
      script: npx @base-cms/website-deployment-tool deploy electricalmarketing.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Electronic Design
      script: npx @base-cms/website-deployment-tool deploy electronicdesign.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Electronic Design
      script: npx @base-cms/website-deployment-tool deploy electronicdesign.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Electrical Wholesaling
      script: npx @base-cms/website-deployment-tool deploy ewweb.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Electrical Wholesaling
      script: npx @base-cms/website-deployment-tool deploy ewweb.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Fleet Owner
      script: npx @base-cms/website-deployment-tool deploy fleetowner.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Fleet Owner
      script: npx @base-cms/website-deployment-tool deploy fleetowner.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Forging
      script: npx @base-cms/website-deployment-tool deploy forgingmagazine.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Forging
      script: npx @base-cms/website-deployment-tool deploy forgingmagazine.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Foundry Management & Technology
      script: npx @base-cms/website-deployment-tool deploy foundrymag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Foundry Management & Technology
      script: npx @base-cms/website-deployment-tool deploy foundrymag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: HPAC Engineering
      script: npx @base-cms/website-deployment-tool deploy hpac.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: HPAC Engineering
      script: npx @base-cms/website-deployment-tool deploy hpac.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Hydraulics & Pneumatics
      script: npx @base-cms/website-deployment-tool deploy hydraulicspneumatics.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Hydraulics & Pneumatics
      script: npx @base-cms/website-deployment-tool deploy hydraulicspneumatics.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: IndustryWeek
      script: npx @base-cms/website-deployment-tool deploy industryweek.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: IndustryWeek
      script: npx @base-cms/website-deployment-tool deploy industryweek.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Machine Design
      script: npx @base-cms/website-deployment-tool deploy machinedesign.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Machine Design
      script: npx @base-cms/website-deployment-tool deploy machinedesign.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Material Handling and Logistics
      script: npx @base-cms/website-deployment-tool deploy mhlnews.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Material Handling and Logistics
      script: npx @base-cms/website-deployment-tool deploy mhlnews.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Microwaves & RF
      script: npx @base-cms/website-deployment-tool deploy mwrf.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Microwaves & RF
      script: npx @base-cms/website-deployment-tool deploy mwrf.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: New Equipment Digest
      script: npx @base-cms/website-deployment-tool deploy newequipment.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: New Equipment Digest
      script: npx @base-cms/website-deployment-tool deploy newequipment.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Power Electronics
      script: npx @base-cms/website-deployment-tool deploy powerelectronics.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Power Electronics
      script: npx @base-cms/website-deployment-tool deploy powerelectronics.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Refrigerated Transporter
      script: npx @base-cms/website-deployment-tool deploy refrigeratedtransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Refrigerated Transporter
      script: npx @base-cms/website-deployment-tool deploy refrigeratedtransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Rental Equipment Register
      script: npx @base-cms/website-deployment-tool deploy rermag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Rental Equipment Register
      script: npx @base-cms/website-deployment-tool deploy rermag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Source Today
      script: npx @base-cms/website-deployment-tool deploy sourcetoday.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Source Today
      script: npx @base-cms/website-deployment-tool deploy sourcetoday.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: T&D World
      script: npx @base-cms/website-deployment-tool deploy tdworld.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: T&D World
      script: npx @base-cms/website-deployment-tool deploy tdworld.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Trailer Body Builders
      script: npx @base-cms/website-deployment-tool deploy trailer-bodybuilders.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Trailer Body Builders
      script: npx @base-cms/website-deployment-tool deploy trailer-bodybuilders.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: American Trucker
      script: npx @base-cms/website-deployment-tool deploy trucker.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: American Trucker
      script: npx @base-cms/website-deployment-tool deploy trucker.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: Truck Fleet MRO
      script: npx @base-cms/website-deployment-tool deploy truckfleetmro.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: Truck Fleet MRO
      script: npx @base-cms/website-deployment-tool deploy truckfleetmro.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]
