language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test
      env:
        - NODE_ENV=test

    - stage: notify_start
      script: deploy/notify-start.sh
      install: skip

    - stage: notify
      script: deploy/notify.sh
      install: skip

    - stage: deploy
      name: GAM Service
      script: deploy/service.js gam gemenon
      install: skip

    - stage: deploy
      name: American Machinist
      script: deploy/index.js americanmachinist.com gemenon
      install: skip

    - stage: deploy
      name: American School & University
      script: deploy/index.js asumag.com gemenon
      install: skip

    - stage: deploy
      name: Bulk Transporter
      script: deploy/index.js bulktransporter.com gemenon
      install: skip

    - stage: deploy
      name: Contracting Business
      script: deploy/index.js contractingbusiness.com gemenon
      install: skip

    - stage: deploy
      name: Contractor
      script: deploy/index.js contractormag.com gemenon
      install: skip

    - stage: deploy
      name: EC&M
      script: deploy/index.js ecmweb.com gemenon
      install: skip

    - stage: deploy
      name: EHS Today
      script: deploy/index.js ehstoday.com gemenon
      install: skip

    - stage: deploy
      name: Electrical Marketing
      script: deploy/index.js electricalmarketing.com gemenon
      install: skip

    - stage: deploy
      name: Electronic Design
      script: deploy/index.js electronicdesign.com gemenon
      install: skip

    - stage: deploy
      name: Electrical Wholesaling
      script: deploy/index.js ewweb.com gemenon
      install: skip

    - stage: deploy
      name: Fleet Owner
      script: deploy/index.js fleetowner.com gemenon
      install: skip

    - stage: deploy
      name: Forging
      script: deploy/index.js forgingmagazine.com gemenon
      install: skip

    - stage: deploy
      name: Foundry Management & Technology
      script: deploy/index.js foundrymag.com gemenon
      install: skip

    - stage: deploy
      name: HPAC Engineering
      script: deploy/index.js hpac.com gemenon
      install: skip

    - stage: deploy
      name: Hydraulics & Pneumatics
      script: deploy/index.js hydraulicspneumatics.com gemenon
      install: skip

    - stage: deploy
      name: IndustryWeek
      script: deploy/index.js industryweek.com gemenon
      install: skip

    - stage: deploy
      name: Machine Design
      script: deploy/index.js machinedesign.com gemenon
      install: skip

    - stage: deploy
      name: Material Handling and Logistics
      script: deploy/index.js mhlnews.com gemenon
      install: skip

    - stage: deploy
      name: Microwaves & RF
      script: deploy/index.js mwrf.com gemenon
      install: skip

    - stage: deploy
      name: New Equipment Digest
      script: deploy/index.js newequipment.com gemenon
      install: skip

    - stage: deploy
      name: Power Electronics
      script: deploy/index.js powerelectronics.com gemenon
      install: skip

    - stage: deploy
      name: Refrigerated Transporter
      script: deploy/index.js refrigeratedtransporter.com gemenon
      install: skip

    - stage: deploy
      name: Rental Equipment Register
      script: deploy/index.js rermag.com gemenon
      install: skip

    - stage: deploy
      name: Source Today
      script: deploy/index.js sourcetoday.com gemenon
      install: skip

    - stage: deploy
      name: T&D World
      script: deploy/index.js tdworld.com gemenon
      install: skip

    - stage: deploy
      name: Trailer Body Builders
      script: deploy/index.js trailer-bodybuilders.com gemenon
      install: skip

    - stage: deploy
      name: American Trucker
      script: deploy/index.js trucker.com gemenon
      install: skip

    - stage: deploy
      name: Truck Fleet MRO
      script: deploy/index.js truckfleetmro.com gemenon
      install: skip
