language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test

  - name: production-started
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production
    if: tag =~ /^v\d+\.\d+\.\d+$/
  - name: production-finished
    if: tag =~ /^v\d+\.\d+\.\d+$/

  - name: staging-started
    if: tag is present
  - name: staging
    if: tag is present
  - name: staging-finished
    if: tag is present

jobs:
  include:
    - stage: test
      env: [NODE_ENV=test]

    - stage: production-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging-started
      name: Deployment Started
      script: npx @base-cms/website-deployment-tool notify-started
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - stage: production
      name: GAM Service
      script: npx @base-cms/website-deployment-tool deploy-service gam gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: GAM Service
      script: npx @base-cms/website-deployment-tool deploy-service gam gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    #############################
    ### vvv ADD SITES HERE vvv ##
    #############################

    - stage: production
      name: americanmachinist.com
      script: npx @base-cms/website-deployment-tool deploy americanmachinist.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: americanmachinist.com
      script: npx @base-cms/website-deployment-tool deploy americanmachinist.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: asumag.com
      script: npx @base-cms/website-deployment-tool deploy asumag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: asumag.com
      script: npx @base-cms/website-deployment-tool deploy asumag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: bulktransporter.com
      script: npx @base-cms/website-deployment-tool deploy bulktransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: bulktransporter.com
      script: npx @base-cms/website-deployment-tool deploy bulktransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: contractingbusiness.com
      script: npx @base-cms/website-deployment-tool deploy contractingbusiness.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: contractingbusiness.com
      script: npx @base-cms/website-deployment-tool deploy contractingbusiness.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: contractormag.com
      script: npx @base-cms/website-deployment-tool deploy contractormag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: contractormag.com
      script: npx @base-cms/website-deployment-tool deploy contractormag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: ecmweb.com
      script: npx @base-cms/website-deployment-tool deploy ecmweb.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: ecmweb.com
      script: npx @base-cms/website-deployment-tool deploy ecmweb.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: ehstoday.com
      script: npx @base-cms/website-deployment-tool deploy ehstoday.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: ehstoday.com
      script: npx @base-cms/website-deployment-tool deploy ehstoday.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: electricalmarketing.com
      script: npx @base-cms/website-deployment-tool deploy electricalmarketing.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: electricalmarketing.com
      script: npx @base-cms/website-deployment-tool deploy electricalmarketing.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: electronicdesign.com
      script: npx @base-cms/website-deployment-tool deploy electronicdesign.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: electronicdesign.com
      script: npx @base-cms/website-deployment-tool deploy electronicdesign.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: ewweb.com
      script: npx @base-cms/website-deployment-tool deploy ewweb.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: ewweb.com
      script: npx @base-cms/website-deployment-tool deploy ewweb.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: fleetowner.com
      script: npx @base-cms/website-deployment-tool deploy fleetowner.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: fleetowner.com
      script: npx @base-cms/website-deployment-tool deploy fleetowner.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: forgingmagazine.com
      script: npx @base-cms/website-deployment-tool deploy forgingmagazine.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: forgingmagazine.com
      script: npx @base-cms/website-deployment-tool deploy forgingmagazine.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: foundrymag.com
      script: npx @base-cms/website-deployment-tool deploy foundrymag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: foundrymag.com
      script: npx @base-cms/website-deployment-tool deploy foundrymag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: hpac.com
      script: npx @base-cms/website-deployment-tool deploy hpac.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: hpac.com
      script: npx @base-cms/website-deployment-tool deploy hpac.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: hydraulicspneumatics.com
      script: npx @base-cms/website-deployment-tool deploy hydraulicspneumatics.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: hydraulicspneumatics.com
      script: npx @base-cms/website-deployment-tool deploy hydraulicspneumatics.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: industryweek.com
      script: npx @base-cms/website-deployment-tool deploy industryweek.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: industryweek.com
      script: npx @base-cms/website-deployment-tool deploy industryweek.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: machinedesign.com
      script: npx @base-cms/website-deployment-tool deploy machinedesign.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: machinedesign.com
      script: npx @base-cms/website-deployment-tool deploy machinedesign.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: mhlnews.com
      script: npx @base-cms/website-deployment-tool deploy mhlnews.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: mhlnews.com
      script: npx @base-cms/website-deployment-tool deploy mhlnews.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: mwrf.com
      script: npx @base-cms/website-deployment-tool deploy mwrf.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: mwrf.com
      script: npx @base-cms/website-deployment-tool deploy mwrf.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: newequipment.com
      script: npx @base-cms/website-deployment-tool deploy newequipment.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: newequipment.com
      script: npx @base-cms/website-deployment-tool deploy newequipment.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: powerelectronics.com
      script: npx @base-cms/website-deployment-tool deploy powerelectronics.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: powerelectronics.com
      script: npx @base-cms/website-deployment-tool deploy powerelectronics.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: refrigeratedtransporter.com
      script: npx @base-cms/website-deployment-tool deploy refrigeratedtransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: refrigeratedtransporter.com
      script: npx @base-cms/website-deployment-tool deploy refrigeratedtransporter.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: rermag.com
      script: npx @base-cms/website-deployment-tool deploy rermag.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: rermag.com
      script: npx @base-cms/website-deployment-tool deploy rermag.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: sourcetoday.com
      script: npx @base-cms/website-deployment-tool deploy sourcetoday.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: sourcetoday.com
      script: npx @base-cms/website-deployment-tool deploy sourcetoday.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: tdworld.com
      script: npx @base-cms/website-deployment-tool deploy tdworld.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: tdworld.com
      script: npx @base-cms/website-deployment-tool deploy tdworld.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: trailer-bodybuilders.com
      script: npx @base-cms/website-deployment-tool deploy trailer-bodybuilders.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: trailer-bodybuilders.com
      script: npx @base-cms/website-deployment-tool deploy trailer-bodybuilders.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: trucker.com
      script: npx @base-cms/website-deployment-tool deploy trucker.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: trucker.com
      script: npx @base-cms/website-deployment-tool deploy trucker.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    - stage: production
      name: truckfleetmro.com
      script: npx @base-cms/website-deployment-tool deploy truckfleetmro.com gemenon
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging
      name: truckfleetmro.com
      script: npx @base-cms/website-deployment-tool deploy truckfleetmro.com gemenon
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]

    #############################
    ### ^^^ ADD SITES HERE ^^^ ##
    #############################

    - stage: production-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=production RANCHER_CLUSTERID=c-gxsr7]

    - stage: staging-finished
      name: Deployment Finished
      script: npx @base-cms/website-deployment-tool notify-finished
      install: skip
      env: [ENVIRONMENT=staging RANCHER_CLUSTERID=c-rc5kp]
